export default [
    {id:1,name:'primeiro',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:1},
    {id:2,name:'segundo',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:2},
    {id:3,name:'terceiro',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:1},
    {id:4,name:'quarto',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:3},
    {id:5,name:'quinto',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:1},
    {id:6,name:'sexto',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:4},
    {id:7,name:'sétimo',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:1},
    {id:8,name:'oitavo',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:4},
    {id:9,name:'nono',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:4},
    {id:10,name:'decimo',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:1},
    {id:11,name:'one',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:2},
    {id:12,name:'two',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:2},
    {id:13,name:'three',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:2},
    {id:14,name:'for',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:2},
    {id:15,name:'five',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:1},
    {id:16,name:'six',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:1},
    {id:17,name:'ultimo',description:'Pão ,Terra,batata,Minhoca, Maionese,Mostarda',lunch:true,price:12.99,classification:4}
]